itemids:
  - '226559' # Foley
  - '226560' # Void
  - '226561' # Condom Cath
  - '226567' # Straight Cath
  - '226627' # OR Urine
  - '226631' # PACU Urine
  - '227489' # GU Irrigant/Urine Volume Out
